/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package design.patterns.study.ezhoon

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

class TestSample {
    @Test
    @DisplayName("샘플용")
    fun testSample() {
        val answer = 0
        assertEquals(0, answer)
    }
}
